<?php
/**
 * Created by PhpStorm.
 * User: Siam
 * Date: 2019/11/22
 * Time: 14:47
 */

namespace EasySwoole\ORM\Tests;

use EasySwoole\Mysqli\QueryBuilder;
use EasySwoole\ORM\Db\Config;
use EasySwoole\ORM\Db\Connection;
use EasySwoole\ORM\DbManager;
use PHPUnit\Framework\TestCase;

class ErrorTest extends TestCase
{
    /**
     * @var $connection Connection
     */
    protected $connection;
    protected $tableName = 'user_test_list';
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $config = new Config(MYSQL_CONFIG);
        $this->connection = new Connection($config);
        DbManager::getInstance()->addConnection($this->connection);
        $connection = DbManager::getInstance()->getConnection();
        $this->assertTrue($connection === $this->connection);
    }


    public function testAdd()
    {
        $model = TestUserModel::create();
        $testUserModel = $model->where("xxx", 1)->get("");
        $this->assertNull($testUserModel);
        if ($model->lastQueryResult()->getLastErrorNo() !== 0 ){
            $this->assertIsString($model->lastQueryResult()->getLastError());
        }

    }
}