<?php
/**
 * Created by PhpStorm.
 * User: Siam
 * Date: 2020/7/22 0022
 * Time: 21:39
 */

namespace EasySwoole\ORM\Tests;


use EasySwoole\Mysqli\Client;
use EasySwoole\ORM\Db\Config;
use EasySwoole\ORM\Db\Connection;
use EasySwoole\ORM\DbManager;
use EasySwoole\ORM\Exception\Exception;
use EasySwoole\ORM\Tests\models\TestUserModel;
use EasySwoole\Pool\Exception\PoolEmpty;
use PHPUnit\Framework\TestCase;

class InjectionClientSchema extends TestCase
{
    /**
     * @var $connection Connection
     */
    protected $connection;
    protected $tableName = 'user_test_list';

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $config           = new Config(MYSQL_CONFIG);
        $this->connection = new Connection($config);
        DbManager::getInstance()->addConnection($this->connection);
        $connection = DbManager::getInstance()->getConnection();
        $this->assertTrue($connection === $this->connection);
    }

    public function testGet()
    {
        try {
            DbManager::getInstance()->invoke(function (Client $client) {
                $model = TestUserModel::create()->setExecClient($client);
                $model->schemaInfo(FALSE);
                // var_dump($model->schemaInfo(FALSE));
            });
        } catch (Exception $e) {
        } catch (PoolEmpty $e) {
        } catch (\Throwable $e) {
        }

    }
}