<?php
/**
 * 链接池心跳检测等
 * User: Siam
 * Date: 2020/3/4 0004
 * Time: 21:39
 */

namespace EasySwoole\ORM\Tests;


use EasySwoole\ORM\Db\Config;
use EasySwoole\ORM\Db\Connection;
use EasySwoole\ORM\DbManager;
use PHPUnit\Framework\TestCase;

class PoolIntervalCheckTest extends TestCase
{

    /**
     * @var $connection Connection
     */
    protected $connection;
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $config = new Config(MYSQL_CONFIG);
        $config->setAutoPing(1);
        $this->connection = new Connection($config);
        DbManager::getInstance()->addConnection($this->connection);
        $connection = DbManager::getInstance()->getConnection();
        $this->assertTrue($connection === $this->connection);
    }

    public function testOne()
    {
        DbManager::getInstance()->getConnection()->getClientPool()->keepMin(1);
        $item = DbManager::getInstance()->getConnection()->getClientPool()->getObj();
        sleep(2);
        $res = DbManager::getInstance()->getConnection()->getClientPool()->itemIntervalCheck($item);
        $this->assertEquals(true,$res );
    }
}