<?php
/**
 * Created by PhpStorm.
 * User: Siam
 * Date: 2019/11/28
 * Time: 15:43
 */

namespace EasySwoole\ORM\Tests;


use PHPUnit\Framework\TestCase;
use Swoole\Coroutine\MySQL;


use EasySwoole\ORM\Tests\models\TestUserListModel;
use EasySwoole\ORM\Tests\models\TestUserModel;
use EasySwoole\ORM\Tests\models\TestTimeStampModel;
use EasySwoole\ORM\Tests\models\TestFunctionFieldNameModel;
use EasySwoole\ORM\Tests\models\TestRelationModel;
use EasySwoole\ORM\Tests\models\TestUserEventModel;
use EasySwoole\ORM\Tests\models\TestUserListGetterModel;

class SwooleTest extends TestCase
{
    /** @var MySQL */
    protected $client;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $swoole_mysql = new MySQL();
        $swoole_mysql->connect(MYSQL_CONFIG);
        $this->client = $swoole_mysql;
    }

    public function testInsert()
    {
        $false = $this->client->query("insert into user_test_list (ttttt) values (1)");
        $this->assertFalse($false);
    }
}